apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - ingest-configmap.yaml
  - ingest-deployment.yaml
  - ingest-service.yaml
  - dcgm-daemonset.yaml
  - dcgm-service.yaml
  - telegraf-daemonset.yaml
  - validator-cronjob.yaml
