apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ingest-configmap.yaml
  - ingest-deployment.yaml
  - ingest-service.yaml

patchesStrategicMerge:
  - patch-ingest-deployment.yaml
  - patch-ingest-service.yaml
